version: '3.9'

services:
  mkdocs:
    image: thomasve/docs:latest
    container_name: docs
    ports:
      - "4040:4040"

  traefik:
  # The official v2 Traefik docker image
    image: traefik:v2.9
    container_name: traefik
  # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/conf.d/rules.toml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # These rules perform https redirection for prod.
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.priority=10" # disable permanent forwarding for every route
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - "--certificatesresolvers.myresolver.acme.email=${useremail}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - ./rules-infra.toml:/etc/traefik/conf.d/rules.toml
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8090:8081"
