version: '3.9'

services:
  mkdocs:
    image: dansknaw/odissei-docs:0.2.0
    container_name: docs
    volumes:
      - ./docs:/site/docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
