name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build the Docker image
        run: |
          docker build . -t thomasve/odissei-docs:latest
          docker build . -t thomasve/odissei-docs:$GITHUB_SHA
          docker push thomasve/odissei-docs:latest
          docker push thomasve/odissei-docs:$GITHUB_SHA
